"""System constants, enumeration values, and defaults for RACE."""

from enum import Enum


class EventType(str, Enum):
    FAILED_PAYMENT = "failed_payment"
    CHECKOUT_ABANDONMENT = "checkout_abandonment"
    RECURRING_PAYMENT_FAILURE = "recurring_payment_failure"


class FailureClass(str, Enum):
    TEMPORARY_NETWORK = "TEMPORARY_NETWORK"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    GATEWAY_DEGRADATION = "GATEWAY_DEGRADATION"
    EXPIRED_CARD = "EXPIRED_CARD"
    FRAUD_SUSPECTED = "FRAUD_SUSPECTED"
    CUSTOMER_ABANDONMENT = "CUSTOMER_ABANDONMENT"
    UNKNOWN = "UNKNOWN"


class RecoveryStrategy(str, Enum):
    RETRY_NOW = "RETRY_NOW"
    RETRY_LATER = "RETRY_LATER"
    REMINDER_THEN_RETRY = "REMINDER_THEN_RETRY"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    STOP = "STOP"


class CaseState(str, Enum):
    AT_RISK = "AT_RISK"
    DIAGNOSED = "DIAGNOSED"
    ACTION_SELECTED = "ACTION_SELECTED"
    POLICY_APPROVED = "POLICY_APPROVED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    OUTCOME_OBSERVED = "OUTCOME_OBSERVED"
    RECOVERED = "RECOVERED"
    RETRY_ELIGIBLE = "RETRY_ELIGIBLE"
    ESCALATED = "ESCALATED"
    STOPPED = "STOPPED"
    EXECUTION_FAILED = "EXECUTION_FAILED"


class PolicyDecision(str, Enum):
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    ESCALATE_REQUIRED = "ESCALATE_REQUIRED"


# Default System Limits
DEFAULT_MAX_RETRIES: int = 3
DEFAULT_MAX_AUTOMATED_AMOUNT_INR: float = 50000.0
DEFAULT_COOLDOWN_MINUTES: int = 30
DEFAULT_RECOVERY_WINDOW_HOURS: int = 72
